version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    args:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
